app/Http/routes.php
<?php
use Illuminate\Support\Facades\Input;
use UxWeb\SweetAlert\SweetAlert;
use App\Job;
use App\Category;


/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/



Route::group(['middleware' => 'web'], function() {
    Route::resource('admin', 'AdminController');
    Route::get('hr',array('as' => 'hr', 'uses' => 'AdminController@hr'));
    Route::resource('category', 'CategoryController');
    Route::resource('client', 'ClientController');
    Route::resource('job', 'JobController');
    Route::resource('user', 'UserController');
    Route::resource('finance', 'FinanceController');
    Route::resource('notification', 'NotificationController');
    Route::resource('role', 'RoleController');

    Route::get('/', function () {
        //  Alert::message('Robots are working!');

        $job=Job::select('id','title','companyname','image','location','price','jobtype','description','creator_id')->orderby('id','desc')->paginate(5);
        return view('index')->with('job',$job);
    });

    /*Route::get('browsejobs', function () {
        return view('browsejob');
    });*/
    Route::get('browsejobs',array('as' => 'browsejobs', 'uses' => 'JobController@jobs'));
    Route::get('singlejob/{id}',array('as' => 'singlejob/{id}', 'uses' => 'JobController@single'));
    Route::get('singlejob', function () {
        return view('singlejob');
    });


    Route::get('browsecats', function () {
        $cats = Category::all();
        return view('browsecats',compact('cats'));
    });

    Route::post('testing',function(){

        $all=Input::all();
        dd($all);

    });

    /*Route::get('apply', function () {
        return view('jobapplication');
    });*/

    Route::resource('apply', 'JobApplicationController');

    Route::get('test', function (){

        Alert::message('You applied successfully!');

    });

    Route::get('register', function () {
        return view('register');
    });

    Route::get('profile', function () {
        return view('profile');
    });


    Route::post('registeruser',array('as' => 'registeruser', 'uses' => 'UserController@register'));
    Route::post('login',array('as' => 'login', 'uses' => 'UserController@login'));
   // Route::get('logout',array('as' => 'logout', 'uses' => 'UserController@logout'));
    Route::get('logout', 'UserController@logout');


    Route::get('testar',array('as' => 'testar', 'uses' => 'UserController@test'));
    Route::get('logins', function () {
        return view('login');
    });


});

Route::get('testjob',array('as' => 'testjob', 'uses' => 'JobController@showjobs'));


/****API***/
Route::post('api/v1/registration',array('as' => 'api/v1/registration','uses' => 'ApiController@register'));
Route::post('api/v1/login',array('as' => 'api/v1/login','uses' => 'ApiController@login'));
Route::get('api/v1/profile/{id}',array('as' => 'api/v1/profile/{id}','uses' => 'ApiController@profile'));
Route::get('api/v1/jobs',array('as' => 'api/v1/jobs','uses' => 'ApiController@jobs'));
Route::put('api/v1/updateprofile',array('as' => 'api/v1/updateprofile','uses' => 'ApiController@update'));
Route::post('api/v1/attendance',array('as' => 'api/v1/attendance','uses' => 'AttendanceController@attendance'));

Route::get('kemi',array('as' => 'classone', 'uses' => 'StudentController@kemi'));

Route::get('classtwo',array('as' => 'classtwo', 'uses' => 'StudentController@classtwo'));


Route::get('classthree',array('as' => 'classthree', 'uses' => 'StudentController@classthree'));

Route::get('classfour',array('as' => 'classfour', 'uses' => 'StudentController@classfour'));

Route::get('classfive',array('as' => 'classfive', 'uses' => 'StudentController@classfive'));

Route::get('meru',array('as' => 'meru', 'uses' => 'StudentController@meru'));

Route::get('mombasa',array('as' => 'mombasa', 'uses' => 'StudentController@mombasa'));

Route::get('nakuru',array('as' => 'nakuru', 'uses' => 'StudentController@nakuru'));

Route::get('kisumu',array('as' => 'kisumu', 'uses' => 'StudentController@kisumu'));
Route::get('attendance',array('as' => 'attendance', 'uses' => 'AttendanceController@index'));









Route::auth();
Route::get('user/activation/{token}', 'Auth\AuthController@activateUser')->name('user.activate');


Route::get('/home', 'HomeController@index');



Route::get('auth/{provider}', 'Auth\AuthController@redirectToProvider');
Route::get('auth/{provider}/callback', 'Auth\AuthController@handleProviderCallback');

resources/views/browsecats.blade.php
@include('includes.header')

<body>
<div id="wrapper">


@include('includes.nav')

<!-- Titlebar
================================================== -->
<div id="titlebar" class="photo-bg" style="background-image: url(images/all-categories-photo.jpg);">
	<div class="container">
		<div class="ten columns">
			<h2>All Categories</h2>
		</div>

		<div class="six columns">
			<a href="add-job.html" class="button">Post a Job, It’s Free!</a>
		</div>

	</div>
</div>


<!-- Content
================================================== -->
<div id="categories">
	<!-- Categories Group -->
	<div class="categories-group">
		<div class="container">
			<div class="four columns"><h4>Web, Software & IT</h4></div>
			<div class="four columns">
				@foreach($cats as $cat)
				<ul>
					 <li><a href={{$cat['name']}}></a></li>


				</ul>
				@endforeach
			</div>
			<div class="four columns">
				<ul>
					<li><a href="#">MySQL</a></li>
					<li><a href="#">JavaScript</a></li>
					<li><a href="#">Software</a></li>
					<li><a href="#">Website Design</a></li>
					<li><a href="#">Programming</a></li>
					<li><a href="#">SEO</a></li>
					<li><a href="#">Java</a></li>
				</ul>
			</div>
			<div class="four columns">
				<ul>
					<li><a href="#">CSS</a></li>
					<li><a href="#">HTML5</a></li>
					<li><a href="#">Web Development</a></li>
					<li><a href="#">Web Design</a></li>
					<li><a href="#">eCommerce</a></li>
				</ul>

			</div>
		</div>
	</div>

	<!-- Categories Group -->
	<div class="categories-group">
		<div class="container">
			<div class="four columns"><h4>Design, Art & Multimedia</h4></div>
			<div class="four columns">
				<ul>
					<li><a href="#">Design</a></li>
					<li><a href="#">Logo Design</a></li>
					<li><a href="#">Graphic Design</a></li>
					<li><a href="#">Video</a></li>
					<li><a href="#">Adnimation</a></li>
					<li><a href="#">Adobe Photoshop</a></li>
					<li><a href="#">Illustration</a></li>
				</ul>
			</div>
			<div class="four columns">
				<ul>
					<li><a href="#">Art</a></li>
					<li><a href="#">3D</a></li>
					<li><a href="#">Adobe Illustrator</a></li>
					<li><a href="#">Drawing</a></li>
					<li><a href="#">Web Design</a></li>
					<li><a href="#">Cartoon</a></li>
					<li><a href="#">Graphics</a></li>
				</ul>
			</div>
			<div class="four columns">
				<ul>
					<li><a href="#">Fashion Design</a></li>
					<li><a href="#">WordPress</a></li>
					<li><a href="#">Editing</a></li>
					<li><a href="#">Writing</a></li>
					<li><a href="#">T-Shirt Design</a></li>
				</ul>
			</div>
		</div>
	</div>

	<!-- Categories Group -->
	<div class="categories-group">
		<div class="container">
			<div class="four columns"><h4>Sales & Marketing</h4></div>
			<div class="four columns">
				<ul>
					<li><a href="#">Display Advertising</a></li>
					<li><a href="#">Email Marketing</a></li>
					<li><a href="#">Lead Generation</a></li>
					<li><a href="#">Market & Customer Research</a></li>
				</ul>
			</div>
			<div class="four columns">
				<ul>
					<li><a href="#">Marketing Strategy</a></li>
					<li><a href="#">Public Relations</a></li>
					<li><a href="#">Telemarketing & Telesales</a></li>
					<li><a href="#">Other - Sales & Marketing</a></li>
				</ul>
			</div>
			<div class="four columns">
				<ul>
					<li><a href="#">SEM - Search Engine Marketing</a></li>
					<li><a href="#">SEO - Search Engine Optimization</a></li>
					<li><a href="#">SMM - Social Media Marketing</a></li>
				</ul>
			</div>
		</div>
	</div>

</div>


@include('includes.footer')

resources/views/browsejob.blade.php
@include('includes.header')

<body>
<div id="wrapper">

@include('includes.nav2')


<!-- Titlebar
================================================== -->
<div id="titlebar"  style="margin-top:15px;">
	<div class="container">
		<div class="ten columns">
			<!--<span>We found 1,412 jobs matching:</span>-->

		</div>

		<div class="six columns">
			<!--<a href="add-job.html" class="button">Post a Job, It’s Free!</a>-->
		</div>

	</div>
</div>


<!-- Content
================================================== -->
<div class="container">
	<!-- Recent Jobs -->
	<div class="eleven columns">
	<div class="padding-right">
		
		<form action="#" method="get" class="list-search">
			<button><i class="fa fa-search"></i></button>
			<input type="text" placeholder="job title, keywords or company name" value=""/>
			<div class="clearfix"></div>
		</form>

		<ul class="job-list full">

			@foreach($job as $jobs)
			<li><a href="{{ URL::to('singlejob')}}/{{$jobs->id}}">
					<img src="{{ $jobs->image}}"> </img>

				<div class="job-list-content">
					<h4>{{$jobs->title}} <span class="full-time">{{$jobs->jobtype}}</span></h4>
					<div class="job-icons">
						<span><i class="fa fa-briefcase"></i> {{$jobs->companyname}}</span>
						<span><i class="fa fa-map-marker"></i> {{$jobs->location}}</span>
						<span><i class="fa fa-money"></i>{{$jobs->price}}</span>
					</div>
					<p>{{$jobs->description}}</p>
				</div>
				</a>
				<div class="clearfix"></div>
			</li>
			@endforeach

			
	

		
		</ul>
		<div class="clearfix"></div>

		<div class="pagination-container">
		
			<nav class="pagination">
					{{$job->render() }}
				
				<!--<ul>
					<li><a href="#" class="current-page">1</a></li>
					<li><a href="#">2</a></li>
					<li><a href="#">3</a></li>
					<li class="blank">...</li>
					<li><a href="#">22</a></li>
				</ul>-->
			</nav>

			<!--<nav class="pagination-next-prev">
				<ul>
					<li><a href="#" class="prev">Previous</a></li>
					<li><a href="#" class="next">Next</a></li>
				</ul>
			</nav>-->
		</div>

	</div>
	</div>


	<!-- Widgets -->
	<div class="five columns">

		<!-- Sort by -->
		<div class="widget">
			<h4>Sort by</h4>

			<!-- Select -->
			<select data-placeholder="Choose Category" class="chosen-select-no-single">
				<option selected="selected" value="recent">Newest</option>
				<option value="oldest">Oldest</option>
				<option value="expiry">Expiring Soon</option>
				<option value="ratehigh">Hourly Rate – Highest First</option>
				<option value="ratelow">Hourly Rate – Lowest First</option>
			</select>

		</div>

		

		<!-- Job Type -->
		<div class="widget">
			<h4>Job Type</h4>

			<ul class="checkboxes">
				<li>
					<input id="check-1" type="checkbox" name="check" value="check-1" checked>
					<label for="check-1">Accounts</label>
				</li>
				<li>
					<input id="check-2" type="checkbox" name="check" value="check-2">
					<label for="check-2">Web Designing <span>(312)</span></label>
				</li>
				<li>
					<input id="check-3" type="checkbox" name="check" value="check-3">
					<label for="check-3"> Music Production<span>(269)</span></label>
				</li>
				<li>
					<input id="check-4" type="checkbox" name="check" value="check-4">
					<label for="check-4">Internship <span>(46)</span></label>
				</li>
				<li>
					<input id="check-5" type="checkbox" name="check" value="check-5">
					<label for="check-5">Freelance <span>(119)</span></label>
				</li>
			</ul>

		</div>



	</div>
	<!-- Widgets / End -->


</div>


@include('includes.footer')

resources/views/createjob.blade.php
@include('includes.addjob')


    <!-- Content
    ================================================== -->
    <div class="container">

        <!-- Submit Page -->
        <div class="sixteen columns">
            <div class="submit-page">
            {{Form::open(array('route'=>array('job.store'),'method'=>'post', 'files'=>'true'))}}

              {{--  <!-- Email -->
                <div class="form">
                    <h5>Your Email</h5>
                    <input class="search-field" type="text" name="email" value="{{old('email')}}" id="email" placeholder="mail@example.com" />
                    <span class="errors" style="color:red;"> {{ $errors->first('email')}}</span>

                </div>--}}

                <!-- Title -->
                <div class="form">
                    <h5>Job Title</h5>
                    <input class="search-field" type="text" placeholder="" name="title" id="title" value="{{old('title')}}"/>
                    <span class="errors" style="color:red;"> {{ $errors->first('title')}}</span>

                </div>

                <!-- Location -->
                <div class="form">
                    <h5>Location <span>(optional)</span></h5>
                    <input class="search-field" type="text" name="location" placeholder="e.g. London" value="{{old('location')}}"/>
                    <p class="note">Leave this blank if the location is not important</p>
                    <span class="errors" style="color:red;"> {{ $errors->first('location')}}</span>

                </div>
                anthony@codigital.co.ke

                <!-- Job Type -->
                <div class="form">
                    <h5>Job Type</h5>
                    <select data-placeholder="Full-Time" name="jobtype" value="{{old('jobtype')}}" class="chosen-select-no-single">
                        <option value="Full-Time">Full-Time</option>
                        <option value="Part-Time">Part-Time</option>
                        <option value="Internship">Internship</option>
                        <option value="Freelance">Freelance</option>
                    </select>
                </div>


                <!-- Choose Category -->
                <div class="form">
                    <div class="select">
                        <h5>Category</h5>
                        <select data-placeholder="Choose Categories" name="cat_id" id="cat_id"  class="chosen-select" multiple>
                            @foreach($title as $titles)

                                <option value="{{$titles->name}}">{{$titles->name}}</option>
                            @endforeach
                        </select>

                    </div>
                </div>

                <!-- Tags -->
                <div class="form">
                    <h5>Budget <span></span></h5>
                    <input class="search-field" type="text" name="price" value="{{old('price')}}" placeholder="e.g. 1000ksh or 200-500ksh" value=""/>
                    <span class="errors" style="color:red;"> {{ $errors->first('price')}}</span>

                </div>


                <!-- Description -->
                <div class="form">
                    <h5>Description</h5>
                    <textarea class="WYSIWYG" name="description" value="{{old('description')}}" cols="40" rows="3" id="summary" spellcheck="true"></textarea>
                </div>

                <!-- Application email/url -->
                <div class="form">
                    <h5>Application Email / URL</h5>
                    <input type="text" name="applicationlink" value="{{ old ('applicationlink')}}" placeholder="Enter an email address or website URL"/>
                </div>

                <!-- TClosing Date -->
                <div class="form">
                    <h5>Closing Date <span>(optional)</span></h5>
                    <input data-role="date"  name="deadline" value="{{old('deadline')}}" type="text" placeholder="yyyy-mm-dd">
                    <p class="note">Deadline for new applicants.</p>
                </div>


                <!-- Company Details -->
                <div class="divider"><h3>Company Details</h3></div>

                <!-- Company Name -->
                <div class="form">
                    <h5>Company Name</h5>
                    <input type="text" name="companyname" value="{{old('companyname')}}" placeholder="Enter the name of the company">
                </div>

                <!-- Website -->
                <div class="form">
                    <h5>Website <span>(optional)</span></h5>
                    <input type="text" name="website" value="{{old('website')}}" placeholder="http://">
                </div>

                <!-- Teagline -->
                <div class="form">
                    <h5>Tagline <span>(optional)</span></h5>
                    <input type="text" name="tagline" value="{{old('tagline')}}" placeholder="Briefly describe your company">
                </div>

                <!-- Twitter -->
                <div class="form">
                    <h5>Twitter Username <span>(optional)</span></h5>
                    <input type="text" name="twitter" value="{{old('twitter')}}" placeholder="@yourcompany">
                </div>

                <!-- Logo -->
                <div class="form">
                    <h5>Logo <span>(optional)</span></h5>
                    <label class="upload-btn">
                        <input type="file" name="image" value="{{old('image')}}" multiple />
                        <i class="fa fa-upload"></i> Browse
                    </label>
                    <span class="fake-input">No file selected</span>
                </div>
                <div class="form-group">
                    <input type="submit" class="btn btn-primary"  value="submit">
                </div>
                {{Form::close()}}

            </div>
        </div>

    </div>
t

    <!-- Footer
    ================================================== -->
    <div class="margin-top-60"></div>

    @include('includes.footer')

    <!-- Back To Top Button -->
    <div id="backtotop"><a href="#"></a></div>

</div>
<!-- Wrapper / End -->
<!-- -->

<!-- Scripts
================================================== -->



</body>

<!-- Mirrored from www.vasterad.com/themes/workscout/add-job.html by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 20 Apr 2017 13:46:07 GMT -->
</html>

resources/views/home.blade.php
@extends('layouts.app')

@section('content')

@endsection

resources/views/jobapplication.blade.php
@include('includes.header')

<body>
<div id="wrapper">

@include('includes.nav2')


<!-- Titlebar
================================================== -->
    <div id="titlebar" style="margin-top:15px;">
        <div class="container">
            <div class="ten columns">
                <!--<span>We found 1,412 jobs matching:</span>-->
                <!--********************************************************** here am suposed to post the category of the job******************************-->
                <h4>Web, Software & IT</h4>
            </div>

            <div class="six columns">
                <!--<a href="add-job.html" class="button">Post a Job, It’s Free!</a>-->
            </div>

        </div>
    </div>


    <!-- Content
    ================================================== -->
    <div class="container">
        <!-- Recent Jobs -->
        <div class="eleven columns">
            <div class="padding-right">
<div id="small-dialog" class="">
    <div class="small-dialog-content">
        <div class="small-dialog-headline">
            <h2>Apply For This Job</h2>
        </div>
        {{Form::open(array('url'=>'testing','class'=>''))}}
            <input type="text" name="fullname" id="fullname" value="{{old('fullname')}}"  placeholder="amount"/>
            <input type="text"  name="email" id="email" value="{{old('email')}}" placeholder="Time" />
            <textarea  name="message" value="{{old('message')}}" id="message" placeholder="Your message / cover letter sent to the employer"></textarea>

            <!-- Upload CV -->
            <div class="upload-info"><strong>Upload your CV (optional)</strong> <span>Max. file size: 5MB</span></div>
            <div class="clearfix"></div>

            <label class="upload-btn">
                <input type="file" name="resume" id="resume" value="{{old('resume')}}" multiple />
                <i class="fa fa-upload"></i> Browse
            </label>
            <span class="fake-input">No file selected</span>

            <div class="divider"></div>

            <button type="submit" class="submit send">Send Application</button>
        {{Form::close()}}

    </div>

</div>
                </div>
            </div>
        </div>
    </div>
@include('includes.footer')

resources/views/login.blade.php
@extends('includes.nav')


@section('content')
    @include('includes.loginheader')
    <body style="background-image: url(assets/1.jpg)">

        <!-- Top content -->
        <header class="transparent sticky-header full-width">
<div class="container">
    <div class="sixteen columns">
    
        <!-- Logo -->
        <div id="logo">
            <h1><a href="index.html"><img src="images/logo.png" alt="Y Hub" /></a></h1>
        </div>

        <!-- Menu -->
  @include('includes.nav')

        <!-- Navigation -->
        <div id="mobile-navigation">
            <a href="#menu" class="menu-trigger"><i class="fa fa-reorder"></i> Menu</a>
        </div>

    </div>
</div>
</header>
<div class="clearfix"></div>
        <div class="top-content">
        	
            <div class="inner-bg">

                <div class="container">
                    <div class="row">
                        <div class="col-sm-8 col-sm-offset-2 text">
                            <h1><strong style="color:white;">Y Hub</strong> </h1>
                            <div class="description">

                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-6 col-sm-offset-3 form-box">
                        	<div class="form-top">
                        		<div class="form-top-left">
                        			<h3>Login to our site</h3>
                            		<p>Enter your username and password to log on:</p>


                        		</div>
                        		<div class="form-top-right">
                        			<i class="fa fa-key"></i>
                        		</div>
                            </div>
                            <div class="form-bottom">
								{{Form::open(array('url'=>'login','class'=>'login-form'))}}

                                <div class="form-group">
			                    		<label class="sr-only" for="form-username">Username</label>
			                        	<input type="email" name="email" placeholder="Username..." class="form-username form-control" id="form-username">
			                        </div>
			                        <div class="form-group">
			                        	<label class="sr-only" for="form-password">Password</label>
			                        	<input type="password" name="password" placeholder="Password..." class="form-password form-control" id="form-password">
			                        </div>
								<input type="submit" value="Sign In" class="btn btn-success"/>
			                     
			                    {{Form::close()}}
		                    </div>
                        </div>
                    </div>
                    <div class="row">
                    <h5><a href="{{URL::to('register')}}">...Not registered click here to register:</a></h5>
                        <div class="col-sm-6 col-sm-offset-3 social-login">
                        	<h3>...or login with:</h3>
                        	<div class="social-login-buttons">
	                        	<a class="btn btn-link-1 btn-link-1-facebook" href="#">
	                        		<i class="fa fa-facebook"></i> Facebook
	                        	</a>
	                        	<a class="btn btn-link-1 btn-link-1-twitter" href="#">
	                        		<i class="fa fa-twitter"></i> Twitter
	                        	</a>
	                        	<a class="btn btn-link-1 btn-link-1-google-plus" href="#">
	                        		<i class="fa fa-google-plus"></i> Google Plus
	                        	</a>
                        	</div>
                        </div>
                    </div>
                </div>
            </div>
            
        </div>

resources/views/managejob.blade.php
@include('includes.addjob')


<!-- Titlebar
================================================== -->
<div id="titlebar" class="single">
    <div class="container">

        <div class="sixteen columns">
            <h2>Manage Jobs</h2>
            <nav id="breadcrumbs">
                <ul>
                    <li>You are here:</li>
                    <li><a href="#">Home</a></li>
                    <li>Job Dashboard</li>
                </ul>
            </nav>
        </div>

    </div>
</div>


<!-- Content
================================================== -->
<div class="container">

    <!-- Table -->
    <div class="sixteen columns">

        <p class="margin-bottom-25">Your listings are shown in the table below. Expired listings will be automatically removed after 30 days.</p>

        <table class="manage-table responsive-table">

            <tr>
                <th><i class="fa fa-file-text"></i> Title</th>
                <th><i class="fa fa-check-square-o"></i>Description</th>
                <th><i class="fa fa-calendar"></i> Budget </th>
                <th><i class="fa fa-calendar"></i> Deadline</th>
                <th><i class="fa fa-user"></i>Bids</th>
                <th></th>
            </tr>

            <!-- Item #1 -->
            @foreach($job as $jobs)
            <tr>
              <td class="title">{{$jobs->title}}</td>

                <td class="centered">{{$jobs->description}}</td>

                <td>{{$jobs->price}}</td>
                <td>{{$jobs->deadline}}</td>
                <td></td>{{$jobs->bids}}</td>
                <td class="action">
                <a><i class="fa fa-pencil"></i>{!! link_to_route('job.edit','Edit',array($jobs->id),array('class'=>'btn btn-primary btn-sm')) !!} </a>
                <a><i class="fa fa-remove"></i>{!! Form::open(['method' => 'DELETE', 'route' => ['job.destroy', $jobs->id]]) !!}
                    {!! Form::submit('Delete',['class'=>'btn btn-danger btn-sm']) !!}
                    {!! Form::close() !!}
                </a>

                </td>
            </tr>
           @endforeach

        </table>

        <br>
        <a href="{{ url::to('job/create') }}" class="button">Add Job</a>


    </div>

</div>

@include('includes.footer')